In [1]:
import json
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
# load Creadit/loan dataset
df= pd.read_csv(r'/Users/tinapham/Downloads/IDA_Statement_of_Credits_and_Grants__-_Latest_Available_Snapshot.csv', sep=',')

In [6]:
# Check for datatype 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10225 entries, 0 to 10224
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   End of Period                    10225 non-null  object
 1   Credit Number                    10225 non-null  object
 2   Region                           10225 non-null  object
 3   Country Code                     10225 non-null  object
 4   Country                          10225 non-null  object
 5   Borrower                         10225 non-null  object
 6   Credit Status                    10225 non-null  object
 7   Service Charge Rate              7939 non-null   float64
 8   Currency of Commitment           10225 non-null  object
 9   Project ID                       10225 non-null  object
 10  Project Name                     10224 non-null  object
 11  Original Principal Amount (US$)  10225 non-null  float64
 12  Cancelled Amount (US$)           10225 non-null  float64
 13  Undisbursed Amount (US$)         10225 non-null  float64
 14  Disbursed Amount (US$)           10225 non-null  float64
 15  Repaid to IDA (US$)              10225 non-null  float64
 16  Due to IDA (US$)                 10225 non-null  float64
 17  Exchange Adjustment (US$)        10225 non-null  int64
 18  Borrower's Obligation (US$)      10225 non-null  float64
 19  Sold 3rd Party (US$)             10225 non-null  float64
 20  Repaid 3rd Party (US$)           10225 non-null  float64
 21  Due 3rd Party (US$)              10225 non-null  int64
 22  Credits Held (US$)               10225 non-null  float64
 23  First Repayment Date             8044 non-null   object
 24  Last Repayment Date              8044 non-null   object
 25  Agreement Signing Date           10080 non-null  object
 26  Board Approval Date              10225 non-null  object
 27  Effective Date (Most Recent)     10123 non-null  object
 28  Closed Date (Most Recent)        10223 non-null  object
 29  Last Disbursement Date           8266 non-null   object
dtypes: float64(11), int64(2), object(17)
memory usage: 2.3+ MB

In [11]:
# Check for missing values
df.isnull().sum()

End of Period                         0
Credit Number                         0
Region                                0
Country Code                          0
Country                               0
Borrower                              0
Credit Status                         0
Service Charge Rate                2286
Currency of Commitment                0
Project ID                            0
Project Name                          1
Original Principal Amount (US$)       0
Cancelled Amount (US$)                0
Undisbursed Amount (US$)              0
Disbursed Amount (US$)                0
Repaid to IDA (US$)                   0
Due to IDA (US$)                      0
Exchange Adjustment (US$)             0
Borrower's Obligation (US$)           0
Sold 3rd Party (US$)                  0
Repaid 3rd Party (US$)                0
Due 3rd Party (US$)                   0
Credits Held (US$)                    0
First Repayment Date               2181
Last Repayment Date                2181
Agreement Signing Date              145
Board Approval Date                   0
Effective Date (Most Recent)        102
Closed Date (Most Recent)             2
Last Disbursement Date             1959
dtype: int64

In [8]:
# Check for duplicate values
df.duplicated().sum()

0

In [10]:
df.head()

,End of Period,Credit Number,Region,Country Code,Country,Borrower,Credit Status,Service Charge Rate,Currency of Commitment,Project ID,...,Repaid 3rd Party (US$),Due 3rd Party (US$),Credits Held (US$),First Repayment Date,Last Repayment Date,Agreement Signing Date,Board Approval Date,Effective Date (Most Recent),Closed Date (Most Recent),Last Disbursement Date
0,06/30/2023 12:00:00 AM,IDA00010,LATIN AMERICA AND CARIBBEAN,HN,Honduras,MINISTERIO DE HACIENDA Y CREDITO PUBLICO,Fully Repaid,0.75,USD,P007335,...,0.0,0,0.0,09/01/1971 12:00:00 AM,03/01/2011 12:00:00 AM,05/12/1961 12:00:00 AM,05/11/1961 12:00:00 AM,06/29/1961 12:00:00 AM,07/31/1967 12:00:00 AM,NaN
1,06/30/2023 12:00:00 AM,IDA00020,EASTERN AND SOUTHERN AFRICA,SD,Sudan,Ministry of Finance & Economic Planning,Repaying,0.75,USD,P002553,...,0.0,0,0.0,07/15/1971 12:00:00 AM,01/15/2011 12:00:00 AM,06/14/1961 12:00:00 AM,06/13/1961 12:00:00 AM,10/19/1961 12:00:00 AM,12/31/1971 12:00:00 AM,NaN
2,06/30/2023 12:00:00 AM,IDA00030,SOUTH ASIA,IN,India,CONTROLLER OF AID ACCOUNTS & AUDIT,Fully Repaid,0.75,USD,P009610,...,0.0,0,0.0,08/15/1971 12:00:00 AM,02/15/2011 12:00:00 AM,06/21/1961 12:00:00 AM,06/20/1961 12:00:00 AM,08/25/1961 12:00:00 AM,06/30/1967 12:00:00 AM,NaN
3,06/30/2023 12:00:00 AM,IDA00040,LATIN AMERICA AND CARIBBEAN,CL,Chile,MINISTERIO DE OBRAS PUBLICAS,Fully Repaid,0.75,USD,P006585,...,0.0,0,0.0,12/01/1971 12:00:00 AM,06/01/2011 12:00:00 AM,06/28/1961 12:00:00 AM,06/27/1961 12:00:00 AM,12/21/1961 12:00:00 AM,12/31/1968 12:00:00 AM,NaN
4,06/30/2023 12:00:00 AM,IDA00050,LATIN AMERICA AND CARIBBEAN,CO,Colombia,MINISTERIO DE HACIENDA Y CREDITO PUBLICO,Fully Repaid,0.75,USD,P006701,...,0.0,0,0.0,12/01/1971 12:00:00 AM,06/01/2011 12:00:00 AM,08/28/1961 12:00:00 AM,08/15/1961 12:00:00 AM,11/25/1961 12:00:00 AM,12/31/1968 12:00:00 AM,NaN

### Cleaning Work
- Convert date from object to datetime in format %Y-%m-%d
- Check if Borrowing country and Guarantor are the same

df[['First Repayment Date','Last Repayment Date','Agreement Signing Date','Board Approval Date', 'Effective Date (Most Recent)','Closed Date (Most Recent)']]

In [17]:
# Identify columns with 'date' in their names
date_columns = [col for col in df.columns if 'date' in col.lower()]

# Step 2: Identified columns and transform data to datetime
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [19]:
df.head()

,End of Period,Credit Number,Region,Country Code,Country,Borrower,Credit Status,Service Charge Rate,Currency of Commitment,Project ID,...,Repaid 3rd Party (US$),Due 3rd Party (US$),Credits Held (US$),First Repayment Date,Last Repayment Date,Agreement Signing Date,Board Approval Date,Effective Date (Most Recent),Closed Date (Most Recent),Last Disbursement Date
0,06/30/2023 12:00:00 AM,IDA00010,LATIN AMERICA AND CARIBBEAN,HN,Honduras,MINISTERIO DE HACIENDA Y CREDITO PUBLICO,Fully Repaid,0.75,USD,P007335,...,0.0,0,0.0,1971-09-01,2011-03-01,1961-05-12,1961-05-11,1961-06-29,1967-07-31,NaT
1,06/30/2023 12:00:00 AM,IDA00020,EASTERN AND SOUTHERN AFRICA,SD,Sudan,Ministry of Finance & Economic Planning,Repaying,0.75,USD,P002553,...,0.0,0,0.0,1971-07-15,2011-01-15,1961-06-14,1961-06-13,1961-10-19,1971-12-31,NaT
2,06/30/2023 12:00:00 AM,IDA00030,SOUTH ASIA,IN,India,CONTROLLER OF AID ACCOUNTS & AUDIT,Fully Repaid,0.75,USD,P009610,...,0.0,0,0.0,1971-08-15,2011-02-15,1961-06-21,1961-06-20,1961-08-25,1967-06-30,NaT
3,06/30/2023 12:00:00 AM,IDA00040,LATIN AMERICA AND CARIBBEAN,CL,Chile,MINISTERIO DE OBRAS PUBLICAS,Fully Repaid,0.75,USD,P006585,...,0.0,0,0.0,1971-12-01,2011-06-01,1961-06-28,1961-06-27,1961-12-21,1968-12-31,NaT
4,06/30/2023 12:00:00 AM,IDA00050,LATIN AMERICA AND CARIBBEAN,CO,Colombia,MINISTERIO DE HACIENDA Y CREDITO PUBLICO,Fully Repaid,0.75,USD,P006701,...,0.0,0,0.0,1971-12-01,2011-06-01,1961-08-28,1961-08-15,1961-11-25,1968-12-31,NaT